import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/reset.css";
import "@/styles/globals.css";
import "@/styles/variables.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Jag är hungrig 💁🏼‍♀️",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="sv">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
